/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/*
 * メモ
 * 配列→List化する時はList変数を作成したあとに配列分ループさせてaddするほうがよい。
 * 型タイプ一致しないなどがクソだるなので。
 */
package howtoList;

import java.util.ArrayList;
import java.util.List;

public class App {
    public List<Integer> getIntList() {

        List<Integer> intList = new ArrayList<Integer>();
        intList.add(1);
        intList.add(5);

        return intList;
    }

    public List<String> getStrList() {

        List<String> strList = new ArrayList<String>();
        strList.add("はじめの一歩");
        strList.add("鬼滅の刃");
        strList.add("ハコヅメ");
        strList.set(1,"煉獄のアニキ");
        return strList;
    }

    protected List<Boolean> getBoolList() {

        List<Boolean> boolList = new ArrayList<Boolean>();
        boolList.add(true);
        return boolList;
    }

    public static void main(String[] args) {

        App app = new App();
        List<Integer> intList = app.getIntList();
        List<String> strList = app.getStrList();
        List<Boolean> boolList = app.getBoolList();

        // List→配列も逆順でおk？
        int[] arrInt = new int[intList.size()];
        for (int i = 0; i < intList.size(); i++) {
            arrInt[i] = intList.get(i);
        }

        System.out.println(intList);
        for (int i = 0; i< arrInt.length; i ++) {
            System.out.println(arrInt[i]);
        }

        System.out.println(strList);
        System.out.println(boolList);
    }
}
